# Generated by Django 3.1.2 on 2020-11-19 14:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='finded_rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('koordinate', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('room_rate', models.IntegerField()),
                ('des', models.TextField()),
            ],
        ),
    ]
