# Generated by Django 3.1.2 on 2020-11-24 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STAY', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finded_rooms',
            old_name='koordinate',
            new_name='coordinate',
        ),
        migrations.RenameField(
            model_name='finded_rooms',
            old_name='des',
            new_name='desc',
        ),
    ]
