# Generated by Django 3.1.2 on 2020-11-24 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STAY', '0002_auto_20201124_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finded_rooms',
            old_name='name',
            new_name='location',
        ),
    ]
