# Generated by Django 3.1.2 on 2020-11-24 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STAY', '0003_auto_20201124_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finded_rooms',
            old_name='desc',
            new_name='des',
        ),
        migrations.RenameField(
            model_name='finded_rooms',
            old_name='location',
            new_name='name',
        ),
    ]
